### ISSUE TITLE
Don't detect OS twice in getPing_msResponse

### ISSUE THREAD

**Issue by ericdorsey** [ericdorsey/HostMAC#17]
Title says it all.

**Comment by bcambl** [comment]
Hey.. I have a branch for that! Needs OSX testing though. Can you help with that?

**Comment by ericdorsey** [comment]
Definitely; let me pull this down and test!

**Comment by ericdorsey** [comment]
Resolved with your now merged e8b9aecb, agreed?

**Comment by bcambl** [comment]
agreed.
