### ISSUE TITLE
Move OS detection into standalone function

### ISSUE THREAD

**Issue by bcambl** [ericdorsey/HostMAC#19]
I am looking at cygwin support and perhaps we should move the os detection into a standalone function.

**Comment by ericdorsey** [comment]
Agreed. Absolutely. 

Related to #17, but let me test your e8b9aec and get that merged real quick

**Comment by ericdorsey** [comment]
Does #48 resolve this, or is there more you'd like to see happen here?

**Comment by bcambl** [comment]
I think so. I am trying to remember what I wanted to do again.. haha
Closed :)

**Comment by bcambl** [comment]
Ah, I remember. I was thinking about taking the os checks out of all the functions completely then create common os command variables. like `ping_cmd` and `arp_cmd`

**Comment by ericdorsey** [comment]
No worries! Feel free to do a new issue or PR for that, or re-open this if you want to have it here. All good with me.
