### ISSUE TITLE
IP validation is broken

### ISSUE THREAD

**Issue by bcambl** [ericdorsey/HostMAC#3]
Currently verifies correct format of IP (ie: xxx.xxx.xxx.xxx)

But this is NOT True:

result = ipCheck('300.300.300.300')
print result
True

**Comment by ericdorsey** [comment]
Okay so... I wasn't accounting for values over 255... ;) 

Lovely Regex. 

Should be resolved merging your 441a0b1 in.

Thanks! 

(Closing, re-open if you disagree)
