### ISSUE TITLE
On Windows, fails to identify it's own MAC addr

### ISSUE THREAD

**Issue by ericdorsey** [ericdorsey/HostMAC#31]
Example, in this run the host I ran this from was Windows, and it had IPv4 addr 192.168.1.2, but it wasn't able to retrieve it's own MAC.

_Output modified to protect the innocent :D_

```
Created output folder /2015-03-22_output
192.168.1.1 Host unreachable No hostname found AA:44:FF:AA:44:00
192.168.1.2 Host unreachable RUNFROMHOST No MAC addr. found
192.168.1.3 Host unreachable No hostname found FF:DD:00:AA:AA:00
```
- [ ] Add Windows specific host MAC detection routine

**Comment by bcambl** [comment]
Prior to the regex changes, this function returned:
`item = "MAC not found, No ARP entry"`

```
C:\Users\testuser>arp -a <current windows ip>
No ARP Entries Found.
```

**Comment by ericdorsey** [comment]
Yeah, the host itself is not included in the `arp` table, but was thinking it would be neat if the script got it anyway, maybe by parsing the `ipconfig /all` `Physical Address` line, or using the output of `getmac`. 

Just an idea.

**Comment by ericdorsey** [comment]
Closing for now as unnecessary.
