### ISSUE TITLE
Move OS specific commands into OS detection function

### ISSUE THREAD

**Issue by bcambl** [ericdorsey/HostMAC#50]
Utilize OS detection function to set OS specific commands for the rest of the script. This removes the need to check OS in certain functions.

**Comment by bcambl** [comment]
I think it would be best to only pass the relevant information to each function instead of the whole dict(). Maybe this should be opened again.

**Comment by ericdorsey** [comment]
Reopened!

**Comment by ericdorsey** [comment]
Do you think passing the whole dict() has much of a performance hit? Or strictly an organizational preference? Or something else?

**Comment by bcambl** [comment]
I was not really thinking from a performance standpoint. If you pass in a dict() then the function is going to be looking for the command via key. If you want to import the script as a module or only import one function, you would need to provide a dict() argument to the script containing the command. Changing it to only pass the relative command to each function is still a bit awkward with the string formatting.. you could just go back to adding the ip to the string. Or perhaps just pass the entire ping command including the ip to the functions.
Another concern is using `shell=True` as it should be avoided if possible.

**Comment by ericdorsey** [comment]
So I did a bit of reading on `shell=True`; fully agree - that's bad news. If we can get it out, let's do it. https://github.com/ericdorsey/HostMAC/issues/52 is my first crack at it.

**Comment by ericdorsey** [comment]
I like the configurability for OS specific commands in `detect_os()` -- I guess the ease of use in the program is the tradeoff for not so much in an `import` context. 

We could port just the raw utility of say `detect_ip()` and `getMac` into it's own (separate `.py` file) utility module (maybe part of this repo, maybe not?). I guess it depends on use cases needed per person.

**Comment by ericdorsey** [comment]
Do you think this should remain open?

**Comment by ericdorsey** [comment]
@bcambl Any thoughts on this staying open, or closing?

**Comment by bcambl** [comment]
Close is good with me.
