### ISSUE TITLE
Add non-interactive mode

### ISSUE THREAD

**Issue by ericdorsey** [ericdorsey/HostMAC#57]
```
$ ./hostmac -start 1 -end 5 -csv -ni
```

Launch, start at x.x.x.1, end at x.x.x.5, create a .CSV, non-interactive (don't show me a menu, just go now)

**Comment by bcambl** [comment]
Technically this functionality already exists by my original  PR. By providing  a `--start` _and/or_  `--end` argument along with the `--all` argument, the query will execute without user prompts.
Perhaps the `--all` argument could be re-factored appropriately. like `-x` and `--execute` with the following assumption:
If no `--start` _and/or_ `--end` is provided, the query will start at the lowest value and and end at the highest value.

When this argument is passed, it should set a flag that is checked before the menu is displayed.

**Comment by ericdorsey** [comment]
Right now, running `$ ./hostmac.py -s 1 -e 10 --all`, it will output for 1-10, it shows the menu, but just launches right into it without user selecting anything, and when it's done, it shows the prompt and waits for user input.

> Perhaps the --all argument could be re-factored appropriately. like -x and --execute with the following assumption:
> If no --start and/or --end is provided, the query will start at the lowest value and and end at the highest value.

So, convert `-a` / `--all` to `-x` / `--execute`, and that automatically launches into the whole 1-254 range?

---

For non interactive, I was thinking of something that doesn't show a menu at all, and doesn't show a menu when it's done (ie, call hostmac w/ desired params, it launches/shows STDOUT, drops you back to $ when done)

**Comment by bcambl** [comment]
Yes that is what the 'flag' would be used for. To determine if the menu should be displayed as well as break the loop to exit the script. I believe that should provide the behavior you are looking for.

**Comment by ericdorsey** [comment]
Are you envisioning both `--all` and `--execute` being an option, or only one of those two?

**Comment by bcambl** [comment]
Just the one command as it will more or less do the same thing. Do you see a use-case for both to exist?

**Comment by ericdorsey** [comment]
No, just making sure I'm on the same page with what you're suggesting. Help would look like this then?

```
optional arguments:
  -h, --help       show this help message and exit
  -c, --csv        log output to csv
  -i IP, --ip IP   specify ip, default: current ip
  -r, --run  no menu, just start using --start and --end range if provided, otherwise 1-254
  -s, --start  start of range
  -e, --end    end of range
```

**Comment by bcambl** [comment]
Yup. I put emphasis on the _and/or_ because one, both, or none are all acceptable when it comes specifying the IP range.

**Comment by ericdorsey** [comment]
Ok cool. Totally agree. 

```
optional arguments:
  -h, --help       show this help message and exit
  -c, --csv        log output to csv
  -i IP, --ip IP   specify ip, default: current ip
  -r, --run  run immediately (no menu) using --start and/or --end range if provided (otherwise defaults to 1-254)
  -s, --start  start of range
  -e, --end    end of range
```

.. oops, e was taken :)

**Comment by ericdorsey** [comment]
See https://github.com/ericdorsey/HostMAC/pull/64/
