### ISSUE TITLE
Combine getAll() and getOne() functions into one new function

### ISSUE THREAD

**Issue by ericdorsey** [ericdorsey/HostMAC#8]
Combine `getAll()` and `getOne()` functions into one new function. Lots of duplicate code in these two functions.

```
displayAndWriteResults(ip, howMany, writeResults):
```

Parameters: 
`ip` = detected IP from earlier
`howMany` = whether user wants results from one IP or whole range (1-254)
`wirteResults` = whether to save results to a CSV in `/output` or just write to screen

**Comment by ericdorsey** [comment]
Maybe `writeResult()` should be it's own function, called from within `displayResult()` instead:

```
# pseudocode

For each in 1-254:
    displayResult(ip, writeToCSV=True)
```

**Comment by bcambl** [comment]
Have a peak at [subnet-scan](https://github.com/bcambl/subnet-scan) to see how I implemented this idea.
I wrote this a week ago before sending you my first pull request. 
The reason I wrote it was due to the amount of style changes I wanted to make to bring it more in-line with my 'personal styleguide' (variable naming, some pep8 linting, white space) as well, different ways of solving the same problems. [good blog post: Contribution Etiquette](http://tirania.org/blog/archive/2010/Dec-31.html) 
I may port some fixes from time to time, but I would rather contribute to this project :) Some code in  [subnet-scan](https://github.com/bcambl/subnet-scan) actually addresses a few current issues (#7 #8) here. If you would like, I would be happy to submit a couple PR for the above issues based off this other project.

how I looped through 1-254:
`for i in range(1, 255):`

**Comment by ericdorsey** [comment]
> good blog post: Contribution Etiquette 

Great article (and interesting comments)! Thanks for sharing that. 

> Have a peak at subnet-scan to see how I implemented this idea.
> I wrote this a week ago before sending you my first pull request. 
> The reason I wrote it was due to the amount of style changes I wanted to make to bring it more in-line with my 'personal styleguide' (variable naming, some pep8 linting, white space) as well, different ways of solving the same problems.

I think it's awesome that you enjoyed the idea enough that it inspired you to create your own! Its really neat to see the different ways people solve the same problem / run with a concept. And thanks for the shout out back to this repo in your readme and the code itself!

Incidentally, what are you using for your PEP8 linting? I could probably do well to brush up on some Python coding conventions. PyCharm is always yelling at me. 

I try to be open to lots of different styles, I've found I can learn a lot by reading other people's code / the way they do things. I tend not to be as hardcore about one way only (like some of the comments in that article discuss), but I to try to have things make sense and be organized. 

> I may port some fixes from time to time, but I would rather contribute to this project :)

Cool! Happy to have any contributions / ideas. You definitely breathed life into something I hadn't looked at in a looooooong time, and inspired me to improve it based on my "today knowledge". So thanks for that and the awesome PR's! This tool is already way cooler than it was a week ago! 

> If you would like, I would be happy to submit a couple PR for the above issues based off this other project.

Definitely! I will address some of your other stuff from yesterday shortly.

**Comment by bcambl** [comment]
I also use PyCharm, so it is yelling at me on this project as well haha.. I definitely am an advocate of the 79 char line length. It is nice to be able to use vi/vim at the cli for quick fixes and not have to deal with lines wrapping my screen ;)

**Comment by ericdorsey** [comment]
Oh, I forgot to say too, one thing I like about what you're doing with [subnet-scan](https://github.com/bcambl/subnet-scan) is this:

```
if __name__ == "__main__":
```

Allows importing directly into an interactive session for testing functions, etc. 

```
C:\Users\Eric Dorsey\Code\subnet-scan>ipython

In [1]: import scan

In [2]: scan.validate_ip('foo')
Out[2]: False

In [3]: scan.validate_ip('192.168.1.1')
Out[3]: True
```

**Comment by bcambl** [comment]
Also allows you to import functions for use in other projects :)

**Comment by ericdorsey** [comment]
For sure! All good things! Was wishing this implementation had the `if __name__ == "__main__":`
setup during some of my testing. Slight bit of rewrite, but it's something from  [subnet-scan](https://github.com/bcambl/subnet-scan) that would, I think, definitely enhance this.

**Comment by bcambl** [comment]
I think I might tackle this one next.

Are you still happy with: 
`displayAndWriteResults(ip, howMany, writeResults)`
or maybe something like this:
`get_results(ip, get_all=False, write=True)`

Should the csv log be written by default or 'stdout only' as default.

**Comment by ericdorsey** [comment]
Nice. I think the naming convention should definitely change to PEP8 standard, so:

```
get_results()
```

And I like your proposed version with the default (most common) arguments. 

---

p.s.
Disregard that organization invite -- was going to use it to add you as assignee, but looks like you have to transfer the repo to do so, so I deleted the organization.
